### ISSUE TITLE
Basic SKU Firewall

### ISSUE THREAD

**Issue by ranjbassi** [adstuart/azure-firewall-deallocate#1]
Hiya,
Firstly thank you for this submission. I tested it in my lab with some adjustments and it works a treat :-). Thank you hopefully my MSDN sub will stretch that bit further without excess Azure F/W daily charges!

Just something to note for Basic SKU, as it uses a management IP, I had to adjust the start F/W script slightly. 

 
##Start Firewall

$azfw = Get-AzFirewall -Name "***F/W Name***" -ResourceGroupName "***RG Group***"
$vnet = Get-AzVirtualNetwork -ResourceGroupName "***RG Group***" -Name "rb81-hub-uksouth"
$publicip = Get-AzPublicIpAddress -Name "***Public IP****" -ResourceGroupName "****RG Group***"
$mgmtIP = Get-AzPublicIpAddress -Name "***MGMT IP***" -ResourceGroupName "****RG Group***"

# Set the Management IP configuration on the firewall
$azfw.IpConfigurations = @($ipConfig)
$azfw.Allocate($vnet, $publicip, $mgmtIP)
Set-AzFirewall -AzureFirewall $azfw

**Comment by adstuart** [comment]
Thanks for your comment, this is also documented publicily now. https://learn.microsoft.com/en-us/azure/firewall/firewall-faq#how-can-i-stop-and-start-azure-firewall
